model:
    _target_: nettcrstruc.model.model.GVPMQA
    node_in_dim: [542, 3]
    node_h_dim: [50, 8]
    edge_in_dim: [32, 1]
    edge_h_dim: [50, 8]
    num_layers: 3
    drop_rate: 0.5
    out_dim: 1
    vector_gating: False
